export default  {
  ADD_TASK: 'ADD_TASK',
  DELETE_TASK: 'DELETE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',

  SET_INPUT_ID: 'SET_INPUT_ID',
  SET_INPUT_DESCRIPCION: 'SET_INPUT_DESCRIPCION',
  SET_INPUT_FECHA_CREACION: 'SET_INPUT_FECHA_CREACION',
  SET_INPUT_VIGENTE:'SET_INPUT_VIGENTE',
  RESET_INPUT:'RESET_INPUT',
}